#!/bin/sh
#
# Starts stt-ihm.
#

SYSCONFDIR=/etc/stt
RUNDIR=/var/run
SBINDIR=/usr/sbin
BINDIR=/usr/bin
LIBDIR=/usr/lib/
WEBSOCKETDIR=${RUNDIR}/ouistiti

start() {
	if [ ! -d ${WEBSOCKETDIR} ]; then
		mkdir ${WEBSOCKETDIR}
		chmod a+rw ${WEBSOCKETDIR}
	fi
	printf "Starting stt-ihm: "
	start-stop-daemon -S -q -m -p ${RUNDIR}/stt-ihm.pid --exec ${BINDIR}/sttCTL -- -D -W ${WEBSOCKETDIR}
	echo "OK"
}
stop() {
	printf "Stopping stt-ihm: "
	if [ -e ${RUNDIR}/stt-ihm.pid ]; then
		start-stop-daemon -K -q -p ${RUNDIR}/stt-ihm.pid
	fi
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

